# Generated by Django 4.2.4 on 2025-03-13 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wildforge_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='spring_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wildforge_api.springproject'),
        ),
        migrations.AddField(
            model_name='activity',
            name='submission_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='meeting',
            name='guest_weight_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='springboardtemplate',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wildforge_api.classroom'),
        ),
        migrations.AlterField(
            model_name='classmember',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Teacher'), (1, 'Student'), (2, 'Guest')], null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'Moderator'), (2, 'Basic'), (3, 'Guest')], null=True),
        ),
    ]
